# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.2"

  config.vm.network "forwarded_port", guest: 9000, host: 9000
  config.vm.network "forwarded_port", guest: 35729, host: 35729

  config.vm.synced_folder "..", "/source"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provision "shell", path: "bootstrap.sh"
end
